- name: install prerequisites
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - git
    - python3.6
    - python3-pip
    - postgresql
    - python-psycopg2
    - npm
    - apache2
    - ansible

- name: Download librehq
  git:
    dest: "{{ librehq_directory }}"
    repo: https://github.com/OpenTechStrategies/librehq

    #- name: Update pip
    #  become: true
    #  pip:
    #    executable: pip3
    #    name: pip

- name: Install pipenv
  become: true
  pip:
    executable: pip3
    name: pipenv

- name: Check to see if pipenv has been run
  ignore_errors: true
  command: "pipenv --venv"
  args:
    chdir: "{{ librehq_directory }}"
  register: pipenv_venv_check_cmd
  changed_when:
    - ('No virtualenv' not in pipenv_venv_check_cmd.stderr)

- name: Run pipenv install
  command: "pipenv install --python 3.6 --dev"
  args:
    chdir: "{{ librehq_directory }}"
  when:
    - ('No virtualenv' in pipenv_venv_check_cmd.stderr)

- name: Install npm packages
  npm:
    path: "{{ librehq_directory }}/client"

- name: Install vue/cli for development ease
  become: true
  npm:
    name: "@vue/cli"
    path: "{{ librehq_directory }}/client"
    global: yes

- name: Build the client
  command: npm run build
  args:
    chdir: "{{ librehq_directory }}/client"

- name: Enable apache proxy http
  become: true
  apache2_module:
    state: present
    name: proxy_http

- name: Add needed postgres user
  become: true
  become_user: postgres
  postgresql_user:
    name: librehq
    password: "{{ db_password }}"
    encrypted: yes

- name: Add core database
  become: true
  become_user: postgres
  postgresql_db:
    name: librehq_core
    owner: librehq

- name: Add wikis database
  become: true
  become_user: postgres
  postgresql_db:
    name: librehq_wikis
    owner: librehq

- name: Copy python configuration
  template:
    src: config.py.j2
    dest: "{{ librehq_directory }}/config.py"

- name: Copy wikis mediawiki configuration
  template:
    src: mwiki_vars.yml.j2
    dest: "{{ librehq_directory }}/wikis/ansible/mediawiki_vars/vars.yml"

- name: Run migrations
  shell: FLASK_APP=librehq FLASK_DEBUG=1 pipenv run flask db upgrade
  args:
    chdir: "{{ librehq_directory }}"
