"""empty message

Revision ID: 2e1efc184b2a
Revises: 5873a625b0fc
Create Date: 2019-03-08 20:49:02.423650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1efc184b2a'
down_revision = '5873a625b0fc'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'name')
    # ### end Alembic commands ###


def upgrade_wikis():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_wikis():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

