"""empty message

Revision ID: 9cd5b4de1ce7
Revises: 2e1efc184b2a
Create Date: 2019-03-08 21:01:50.694115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd5b4de1ce7'
down_revision = '2e1efc184b2a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('corporate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'corporate')
    # ### end Alembic commands ###


def upgrade_wikis():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_wikis():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

