"""empty message

Revision ID: e67288738e06
Revises: 9cd5b4de1ce7
Create Date: 2019-03-09 20:29:30.386021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67288738e06'
down_revision = '9cd5b4de1ce7'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_account',
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], )
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorized_account')
    # ### end Alembic commands ###


def upgrade_wikis():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_wikis():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

