"""empty message

Revision ID: f2507eb38462
Revises: d9d68f3e165c
Create Date: 2018-11-04 04:31:11.022956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2507eb38462'
down_revision = 'd9d68f3e165c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('validated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'validated')
    # ### end Alembic commands ###
