# It needs to be run with command line arguments specifying
# the name and whatnot.  For instance:
#
# ansible-playbook --extra-vars "wiki_name_old=test1 wiki_name_new=test2" mediawiki-rename-wiki.yml

- hosts: mediawiki
  tasks:

  - name: Include variables for rename script
    include_vars: mediawiki_vars/vars.yml

  - name: Move wiki config file to new name
    command: >
      creates="{{ mediawiki_install_directory }}/conf/{{ wiki_name_new }}.yml"
      mv {{ mediawiki_install_directory }}/conf/{{ wiki_name_old }}.yml
      "{{ mediawiki_install_directory }}/conf/{{ wiki_name_new }}.yml"

  - name: Add wiki listing to versions
    lineinfile:
      path: "{{ mediawiki_install_directory }}/conf/versions.yml"
      regexp: "^{{ wiki_name_old }}: mediawiki-1.31.1"
      line: "{{ wiki_name_new }}: mediawiki-1.31.1"
      state: present
