# It needs to be run with command line arguments specifying
# the name and whatnot.  For instance:
#
# ansible-playbook --extra-vars "wiki_name=test1 wiki_db=wikidb1" mediawiki-delete-wiki.yml

- hosts: mediawiki
  tasks:

  - name: Include variables for delete script
    include_vars:
      dir: mediawiki_vars
      ignore_files: [vars.yml.tmpl]
      extensions: [yml]

  - name: Drop database
    become: true
    mysql_db:
      name: "{{ wiki_db }}"
      state: absent

  - name: Remove wikifarm config file
    file:
      state: absent
      path: "{{ mediawiki_install_directory }}/conf/{{ wiki_name }}.yml"

  - name: Remove wiki listing from versions
    lineinfile:
      path: "{{ mediawiki_install_directory }}/conf/versions.yml"
      line: "{{ wiki_name }}: mediawiki-1.31.1"
      state: absent
